### ISSUE TITLE
CI produce emails

### ISSUE THREAD

**Issue by grandmotivator** [opensourcewebsite-org/osw-devops#24]
<img width="490" alt="Screenshot 2022-06-16 at 17 33 50" src="https://user-images.githubusercontent.com/34159182/174052094-e2a67d46-243e-459b-9ce9-6db7c70652f6.png">

<img width="771" alt="Screenshot 2022-07-11 at 13 52 03" src="https://user-images.githubusercontent.com/34159182/178205611-174996da-296d-4e72-a634-b35beb3f03de.png">

1. It is better to disable sending mail for tests.
2. Reconfigure the mail server so that it does not send such mail.

**Comment by A1EF** [comment]
Probably fixed in https://github.com/opensourcewebsite-org/osw-devops/commit/abbbf74a0313ead88c5a0a1fd116790171ace582, https://github.com/opensourcewebsite-org/osw-devops/commit/e9563a2850cab38f1de46680c76b447f0609f0a7, https://github.com/opensourcewebsite-org/osw-devops/commit/8ccbc41de813098a7c964ac9c4f970da5c0b8c49
